name: Blockchain Polling System CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip -r release.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: release.zip

      - name: Install Solidity compiler
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.12/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc
          ls -l /usr/local/bin/solc  # Check if the file exists and has executable permissions
          /usr/local/bin/solc --version  # Verify that the Solidity compiler is executable



      - name: Install Ganache
        run: npm install -g ganache-cli

      - name: Check if MetaMask is installed
        run: |
          if [ -d "$HOME/.config/google-chrome/NativeMessagingHosts" ]; then
            if ls $HOME/.config/google-chrome/NativeMessagingHosts | grep -q metamask; then
              echo "MetaMask is installed."
            else
              echo "MetaMask is not installed."
            fi
          else
            echo "MetaMask is not installed."
          fi

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app

      - name: Unzip artifact for testing
        run: unzip -o release.zip

      - name: Test Solidity
        run: |
          /usr/local/bin/solc --version

      - name: Test Ganache
        run: ganache-cli --version

      - name: Test MetaMask
        run: |
          if [ -d "$HOME/.config/google-chrome/NativeMessagingHosts" ]; then
            if ls $HOME/.config/google-chrome/NativeMessagingHosts | grep -q metamask; then
              echo "MetaMask is installed."
            else
              echo "MetaMask is not installed."
              exit 1
            fi
          else
            echo "MetaMask is not installed."
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from test job
        uses: actions/download-artifact@v2
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip -o release.zip
